#######################################################################################
# A default configuration that will be loaded for all jupyter books
# See the documentation for help and more options: 
# https://jupyterbook.org/customize/config.html

#######################################################################################
# Book settings
title                       : "Computational Neuroscience Sessions"  # The title of the book. Will be placed in the left navbar.
author                      : NABI-SNU  # The author of the book
copyright                   : "By NABI-SNU"  # Copyright year to be placed in the footer
logo                        : tutorials/static/book-logo-hero-image.png  # A path to the book logo
only_build_toc_files        : true


#######################################################################################
# Execution settings
execute:
  execute_notebooks         : force # Whether to execute notebooks at build time. Must be one of ("auto", "force", "cache", "off")
  cache                     : ""    # A path to the jupyter cache that will be used to store execution artifacts. Defaults to `_build/.jupyter_cache/`
  exclude_patterns          : [Bonus_Autoencoders/student/Bonus_Tutorial1.ipynb, Bonus_Autoencoders/student/Bonus_Tutorial2.ipynb, Bonus_Autoencoders/student/Bonus_Tutorial3.ipynb]    # A list of patterns to *skip* in execution (e.g. a notebook that takes a really long time)
  timeout                   : 360    # The maximum time (in seconds) each notebook cell is allowed to run.
  run_in_temp               : false # If `True`, then a temporary directory will be created and used as the command working directory (cwd),
                                    # otherwise the notebook's parent directory will be the cwd.
  allow_errors              : true # If `False`, when a code cell raises an error the execution is stopped, otherwise all cells are always run.
  stderr_output             : show  # One of 'show', 'remove', 'remove-warn', 'warn', 'error', 'severe'

# Parse and render settings
parse:
  myst_enable_extensions:  # default extensions to enable in the myst parser. See https://myst-parser.readthedocs.io/en/latest/using/syntax-optional.html
    - amsmath
    - dollarmath
    - html_image
    - substitution
sphinx:
  config:
    html_show_copyright: false
    html_theme_options:
      footer_content_items:
        - author.html
        - copyright.html
        - extra-footer.html
    html_js_files:
      - theme-toggle.js
      - sidebar-parts.js
    suppress_warnings:
      - mystnb.unknown_mime_type
    templates_path:
      - _templates
    myst_substitutions:
     open_access: "<img alt='Open Access publication' src='../static/Open_Access_logo.png' height=0.8em class='no-scaled-link inline-icon'>"
     closed_access: "<img alt='Closed Access publication' src='../static/Closed_Access_logo.png' height=0.8em class='no-scaled-link inline-icon'>"
#######################################################################################
# HTML-specific settings
html:
  favicon                   : tutorials/static/favicon.png  # A path to a favicon image
  use_edit_page_button      : false  # Whether to add an "edit this page" button to pages. If `true`, repository information in repository: must be filled in
  use_repository_button     : true  # Whether to add a link to your repository button
  use_issues_button         : true  # Whether to add an "open an issue" button
  extra_navbar              : Powered by <a href="https://jupyterbook.org">Jupyter Book</a>  # Will be displayed underneath the left navbar.
  extra_footer              : ""  # Will be displayed underneath the footer.
  google_analytics_id       : ""  # A GA id that can be used to track book views.
  home_page_in_navbar       : true  # Whether to include your home page in the left Navigation Bar
  baseurl                   : ""  # The base URL where your book will be hosted. Used for creating image previews and social links. e.g.: https://mypage.com/mybook/
  comments:
    hypothesis              : false
    utterances              : false
  extra_footer              : By NABI-SNU. This book adapts Neuromatch Academy Computational Neuroscience and NeuroAI materials, with original contributor credits preserved in each lesson.
repository:
  url                       : https://github.com/NABI-SNU/book  # The URL to your book's repository
  path_to_book              : book  # A path to your book's folder, relative to the repository root.
  branch                    : main  # Which branch of the repository should be used when creating links
